FROM library/ubuntu

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages
RUN apt-get update && apt-get install git curl net-tools --assume-yes

# Run masterscript when the container launches
CMD ["./masterscript"]